spring:
  profiles:
    active: ${driving_school_env:dev}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 6661
  tomcat:
    uri-encoding: utf-8
    accept-count: 1000
    max-connections: 500
    threads:
      max: 500
      min-spare: 50
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
log:
  level: info
  moduleName: manage